language: node_js
node_js:
- '6'
sudo: false
deploy:
  provider: heroku
  app: shouldwehirethatdev
  api_key:
    secure: i2HA6vwcQ5MFNsZHZbxkBOEBduUG+3mS/Lsxdv1kavbBu0j17VWwjFgsjpcLd1+egl+nh9g3Ya2XNVY/7JzcW+bVZVQ6Nn83U1YHNcBqcKmli0R5xdachgcj5W65kAVHkMSsHvKGuCwrQom6ULr6EQGb7oouSZa7G3Kp2iiKFfR7tmDJss9dxUNhmvqJ7jo5b+dik/+F+rIMayrEzEPkeNhqHtnQCh9wGLcFTgU+q1sD3tAUmXOte/TK2yaTXQTSzScPjwXsv1afi1BIXpwuozKb9ZJ9tID0Lhyd+lyfHVZ7gZMpDmrkK4qsdHqXsVJLhAwFTMFYNRsh/ipbN5RqayDe+KgT5rD5v/HNEBUsGMga+X4sFZgTiDbBM0zdVA5Kp2pv34c6/VJm23fzv63z/+NMs6w1LgZmSBWnZiMGkLqIrvsr6Dv8bpaH0K1W798VpRVx8B9aKz5/0LkngX/n2E4kAXBp8rCoSOT8Gd+IMvi+XLJivwdaXuAtn33kOy5fZtdMSICoPuR4nmfXp/7djPwg0KJz3yS3TOcBa/ot8nZTq+lB9vO9+agmMDZyM5gArxYJGlIiWcIRVFISyn2yVT8r2EQegi7+WdvEDf7gCFtGmcZ6DvpZy6Yls0JRwd+shaXaUHiUO3f2iwWSp4jxXlu3mRCh6Mmo0Ni8Y+OSwO8=
  on:
    node_js: '6'
    branch: master
